const styles = 
{
    page: {
        minHeight: "100vh",
        backgroundColor: "#0D1B2A",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        fontFamily: "'Inter', system-ui, -apple-system, sans-serif",
    },
    card: {
        backgroundColor: "#1A2B3C",
        padding: "48px 40px 40px",
        width: "100%",
        maxWidth: "360px",
        boxShadow: "0 24px 64px rgba(0,0,0,0.5)",
    },
    brand: {
        display: "flex",
        alignItems: "center",
        gap: "10px",
        marginBottom: "36px",
    },
    brandIcon: {
        width: "32px",
        height: "32px",
        backgroundColor: "#2E86FF",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    },
    brandIconInner: {
        width: "12px",
        height: "12px",
        backgroundColor: "#0D1B2A",
        transform: "rotate(45deg)",
    },
    brandName: {
        fontSize: "15px",
        fontWeight: "700",
        color: "#E8EDF2",
        letterSpacing: "0.08em",
        textTransform: "uppercase",
    },
    heading: {
        fontSize: "24px",
        fontWeight: "700",
        color: "#E8EDF2",
        marginBottom: "6px",
        lineHeight: "1.2",
    },
    subheading: {
        fontSize: "13px",
        color: "#8899AA",
        marginBottom: "36px",
    },
    fieldGroup: {
        marginBottom: "28px",
    },
    label: {
        display: "block",
        fontSize: "11px",
        fontWeight: "600",
        color: "#2E86FF",
        letterSpacing: "0.1em",
        textTransform: "uppercase",
        marginBottom: "8px",
    },
    input: {
        width: "100%",
        background: "transparent",
        border: "none",
        borderBottom: "1px solid #2A3D52",
        padding: "8px 0",
        fontSize: "15px",
        color: "#E8EDF2",
        outline: "none",
        boxSizing: "border-box",
        transition: "border-color 0.15s",
    },
    button: {
        width: "100%",
        padding: "14px",
        backgroundColor: "#2E86FF",
        color: "#fff",
        border: "none",
        borderRadius: "0",
        fontSize: "13px",
        fontWeight: "700",
        letterSpacing: "0.1em",
        textTransform: "uppercase",
        cursor: "pointer",
        marginTop: "8px",
        transition: "background-color 0.15s",
    },
    buttonDisabled: {
        backgroundColor: "#1A4A8A",
        cursor: "not-allowed",
    },
    error: {
        fontSize: "13px",
        color: "#FF5C5C",
        marginTop: "16px",
        textAlign: "center",
    },
    footer: {
        marginTop: "28px",
        paddingTop: "20px",
        borderTop: "1px solid #2A3D52",
        fontSize: "12px",
        color: "#8899AA",
        textAlign: "center",
    },
};

export default styles;